version: 06-25-2019

plugins:
  - ./plugins/netlify-plugin-cypress:
      baseUrl: "${env:SITE}"
      pageLoadTimeout: 60000
  - ./plugins/netlify-plugin-sitemap:
      exclude: "**/dist"
  - ./plugins/netlify-plugin-notify:
      emails:
        - david@netlify.com
        - jim@netlify.com
  # - netlify-cache-plugin:
  #     dir: 'lol-dir'
  #     ttl: 100000
  # - netlify-lighthouse-plugin: true

build:
  lifecycle:
    init:
      - npm run foo
      - export VALUE=lol
      - echo "much wow"
    getCache:
      - echo 'curl custom cache'
    #install: npm install
    build: |
      echo 'Hello Netlify Build!'
      npm run build
    # package:
    #   - zip -q -r .functions/package.zip src node_modules
